spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket_booking_db
    username: root
    password: 12345
  jpa:
    #    hibernate.ddl-auto: update
    #    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

vnpay:
  tnnCode: ${VNPAY_TNNCODE}
  hashSecret: ${VNPAY_HASH_SECRET}


