spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket_booking_db
    username: root
    password: 12345
  jpa:
    #    hibernate.ddl-auto: update
    #    generate-ddl: true
    show-sql: true



app:
  jwt-secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
  jwt-expiration-milliseconds: 604800000


server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
