spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket_booking_db
    username: root
    password: 12345
  jpa:
    #    hibernate.ddl-auto: update
    #    generate-ddl: true
    show-sql: true

  mvc:
    servlet:
      path: /api/v1/auth


server:
  port: 8081